modLoader="javafml"
loaderVersion="[34,)"
license="https://www.gnu.org/licenses/gpl-3.0.en.html"
issueTrackerURL="https://github.com/CoffeeCatRailway/BedCutter/issues"

[[mods]]
modId="bedcutter"
version="1.1.1"
displayName="Bed Cutter"
credits="https://www.reddit.com/r/PhoenixSC/comments/jekp8b/phoenix_can_you_add_this_to_the_game_and_make_it/"
authors="CoffeeCatRailway"
description='''
This mod was an idea I saw on reddit and thought it would be fun to make!
Plus it looked strange :D
'''

[[dependencies.coffeecheese]]
modId="forge"
mandatory=true
versionRange="[34,)"
ordering="NONE"
side="BOTH"
[[dependencies.coffeecheese]]
modId="minecraft"
mandatory=true
versionRange="[1.16.3]"
ordering="NONE"
side="BOTH"