@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package coffeecatrailway.bedcutter.common.capability;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;