@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package coffeecatrailway.bedcutter.client.renderer.entity.layers;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;