@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package coffeecatrailway.bedcutter.client.model;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;