@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package coffeecatrailway.bedcutter.client.renderer.tileentity.itemstack;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;