@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package coffeecatrailway.bedcutter.client.renderer.tileentity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;